version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      APPLICATION_SECURITY_JWT_SECRET_KEY: ${APPLICATION_SECURITY_JWT_SECRET_KEY}
      APPLICATION_SECURITY_JWT_EXPIRATION: ${APPLICATION_SECURITY_JWT_EXPIRATION}
      APPLICATION_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION: ${APPLICATION_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION}
    ports:
      - "8080:8080"
