spring:
  datasource:
    url: jdbc:postgresql://dpg-ciqibr5ph6ej5vghume0-a.frankfurt-postgres.render.com/todo_app_database
    username: todo_app_database_user
    password: d5FqHGrCavNuRBWtTrbAcAlA9a8XmKwB
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days