spring:
  datasource:
    url: jdbc:postgresql://snuffleupagus.db.elephantsql.com/gyqcbvfy
    username: gyqcbvfy
    password: GUejMM9xH8BSSB5n3Cc19C6dSPsnc98A
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days